[tcp] Fixes for Processing of Received ACKs, Receiving Out-of-order Segments, Delayed ACKs, etc.
demikernel/catnip pull request #145
Opened 2022-04-27 08:18 UTC by BrianZill

This PR primarily fixes two major issues: the processing of ACKs we receive, and the handling of data segments we receive out of order.  We now properly handle any ACKs, and not just ones that correspond to our initial packetization.  We also now properly store out-of-order data (including potential FIN) for reinsertion into the data stream when a retransmitted or delayed packet arrives to fill the "hole" in the sequence number space (this was a potential data corruption bug).

This PR also improves when we send ACKs to be RFC 1122 compliant, how/when we update our send window, and the names of some variables to be more understandable.

This check-in contains partial or complete fixes for the Issues #63, #101, #102, #103.

2022-04-27 13:14 UTC, ppenna requested changes
Overall, these changes look OK for me, but I'm not a TCP expert.

Besides the changes that I requested on some dangling comment lines, I have two observations.

First, I'm concerned about exposing fields of some data structures because it breaks encapsulation and favors the construction of tightly coupled subsystems.


Second, these changes break the TCP Ping-Pong test for Catnip LibOS. I have pushed a branch in Demikernel for debugging purposes (https://github.com/demikernel/demikernel/tree/enhancement-contrib-update), but here is what we are getting:

Server
```
EAL: Detected 8 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Auto-detected process type: PRIMARY
EAL: Detected shared linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available 1048576 kB hugepages reported
DPDK reports that 1 ports (interfaces) are available.
Port 1 Link Up - speed 50000 Mbps - full duplex
TRACE [catnip] socket(): domain=2 type=1 protocol=0
TRACE [catnip] bind(): qd=QDesc(0) local=Ipv4Endpoint { addr: 10.2.0.10, port: Port16(12345) }
TRACE [catnip] listen(): qd=QDesc(0) backlog=16
TRACE [catnip] accept(): QDesc(0)
TRACE [catnip] wait2(): qt=QToken(3)
WARN [catnip] Dropped packet: Error 95: "unsupported ETHERTYPE"
DEBUG [catnip] Engine received Ethernet2Header { dst_addr: MacAddress(00-0d-3a-63-23-03), src_addr: MacAddress(fc-bd-67-42-9f-b9), ether_type: Ipv4 }
DEBUG [catnip::protocols::peer] Ipv4 received Ipv4Header { version: 4, ihl: 5, dscp: 0, ecn: 0, total_length: 48, identification: 0, flags: 2, fragment_offset: 0, ttl: 255, protocol: TCP, header_checksum: 26543, src_addr: 10.2.0.11, dst_addr: 10.2.0.10 }
DEBUG [catnip::protocols::tcp::peer] TCP received TcpHeader { src_port: Port16(50951), dst_port: Port16(12345), seq_num: SeqNumber { value: 3585248091 }, ack_num: SeqNumber { value: 0 }, ns: false, cwr: false, ece: false, urg: false, ack: false, psh: false, rst: false, syn: true, fin: false, window_size: 65535, urgent_pointer: 0, num_options: 2, option_list: [MaximumSegmentSize(1458), WindowScale(0), NoOperation, NoOperation, NoOperation] }
DEBUG [catnip::protocols::tcp::peer] Routing to passive connection: Ipv4Endpoint { addr: 10.2.0.10, port: Port16(12345) }
DEBUG [catnip::protocols::tcp::passive_open] Received SYN: TcpHeader { src_port: Port16(50951), dst_port: Port16(12345), seq_num: SeqNumber { value: 3585248091 }, ack_num: SeqNumber { value: 0 }, ns: false, cwr: false, ece: false, urg: false, ack: false, psh: false, rst: false, syn: true, fin: false, window_size: 65535, urgent_pointer: 0, num_options: 2, option_list: [MaximumSegmentSize(1458), WindowScale(0), NoOperation, NoOperation, NoOperation] }
INFO [catnip::protocols::tcp::passive_open] Received advertised MSS: 1458
INFO [catnip::protocols::tcp::passive_open] Received window scale: 0
DEBUG [catnip] Engine received Ethernet2Header { dst_addr: MacAddress(00-0d-3a-63-23-03), src_addr: MacAddress(12-34-56-78-9a-bc), ether_type: Arp }
DEBUG [catnip::protocols::arp::peer] Received ArpHeader { operation: Reply, sender_hardware_addr: MacAddress(12-34-56-78-9a-bc), sender_protocol_addr: 10.2.0.11, target_hardware_addr: MacAddress(00-0d-3a-63-23-03), target_protocol_addr: 10.2.0.10 }
DEBUG [catnip::protocols::arp::peer] reply from `10.2.0.11/12-34-56-78-9a-bc`
DEBUG [catnip::protocols::arp::peer] ARP result available (12-34-56-78-9a-bc)
INFO [catnip::protocols::tcp::passive_open] Advertising MSS: 1500
INFO [catnip::protocols::tcp::passive_open] Advertising window scale: 0
DEBUG [catnip::protocols::tcp::passive_open] Sending SYN+ACK: TcpHeader { src_port: Port16(12345), dst_port: Port16(50951), seq_num: SeqNumber { value: 227472677 }, ack_num: SeqNumber { value: 3585248092 }, ns: false, cwr: false, ece: false, urg: false, ack: true, psh: false, rst: false, syn: true, fin: false, window_size: 65535, urgent_pointer: 0, num_options: 2, option_list: [MaximumSegmentSize(1500), WindowScale(0), NoOperation, NoOperation, NoOperation] }
DEBUG [catnip] Engine received Ethernet2Header { dst_addr: MacAddress(00-0d-3a-63-23-03), src_addr: MacAddress(fc-bd-67-42-9f-b9), ether_type: Ipv4 }
DEBUG [catnip::protocols::peer] Ipv4 received Ipv4Header { version: 4, ihl: 5, dscp: 0, ecn: 0, total_length: 40, identification: 0, flags: 2, fragment_offset: 0, ttl: 255, protocol: TCP, header_checksum: 26551, src_addr: 10.2.0.11, dst_addr: 10.2.0.10 }
DEBUG [catnip::protocols::tcp::peer] TCP received TcpHeader { src_port: Port16(50951), dst_port: Port16(12345), seq_num: SeqNumber { value: 3585248092 }, ack_num: SeqNumber { value: 227472678 }, ns: false, cwr: false, ece: false, urg: false, ack: true, psh: false, rst: false, syn: false, fin: false, window_size: 65535, urgent_pointer: 0, num_options: 0, option_list: [NoOperation, NoOperation, NoOperation, NoOperation, NoOperation] }
DEBUG [catnip::protocols::tcp::peer] Routing to passive connection: Ipv4Endpoint { addr: 10.2.0.10, port: Port16(12345) }
DEBUG [catnip::protocols::tcp::passive_open] Received ACK: TcpHeader { src_port: Port16(50951), dst_port: Port16(12345), seq_num: SeqNumber { value: 3585248092 }, ack_num: SeqNumber { value: 227472678 }, ns: false, cwr: false, ece: false, urg: false, ack: true, psh: false, rst: false, syn: false, fin: false, window_size: 65535, urgent_pointer: 0, num_options: 0, option_list: [NoOperation, NoOperation, NoOperation, NoOperation, NoOperation] }
INFO [catnip::protocols::tcp::passive_open] Window sizes: local 65535, remote 65535
INFO [catnip::protocols::tcp::passive_open] Window scale: local 0, remote 0
DEBUG [catnip] Engine received Ethernet2Header { dst_addr: MacAddress(00-0d-3a-63-23-03), src_addr: MacAddress(fc-bd-67-42-9f-b9), ether_type: Ipv4 }
DEBUG [catnip::protocols::peer] Ipv4 received Ipv4Header { version: 4, ihl: 5, dscp: 0, ecn: 0, total_length: 104, identification: 0, flags: 2, fragment_offset: 0, ttl: 255, protocol: TCP, header_checksum: 26487, src_addr: 10.2.0.11, dst_addr: 10.2.0.10 }
DEBUG [catnip::protocols::tcp::peer] TCP received TcpHeader { src_port: Port16(50951), dst_port: Port16(12345), seq_num: SeqNumber { value: 3585248092 }, ack_num: SeqNumber { value: 227472678 }, ns: false, cwr: false, ece: false, urg: false, ack: true, psh: false, rst: false, syn: false, fin: false, window_size: 65535, urgent_pointer: 0, num_options: 0, option_list: [NoOperation, NoOperation, NoOperation, NoOperation, NoOperation] }
DEBUG [catnip::protocols::tcp::peer] Routing to passive connection: Ipv4Endpoint { addr: 10.2.0.10, port: Port16(12345) }
TRACE [catnip] pop(): qd=QDesc(1)
TRACE [catnip] wait2(): qt=QToken(3)
DEBUG [catnip] Engine received Ethernet2Header { dst_addr: MacAddress(00-0d-3a-63-23-03), src_addr: MacAddress(fc-bd-67-42-9f-b9), ether_type: Ipv4 }
DEBUG [catnip::protocols::peer] Ipv4 received Ipv4Header { version: 4, ihl: 5, dscp: 0, ecn: 0, total_length: 104, identification: 0, flags: 2, fragment_offset: 0, ttl: 255, protocol: TCP, header_checksum: 26487, src_addr: 10.2.0.11, dst_addr: 10.2.0.10 }
DEBUG [catnip::protocols::tcp::peer] TCP received TcpHeader { src_port: Port16(50951), dst_port: Port16(12345), seq_num: SeqNumber { value: 3585248092 }, ack_num: SeqNumber { value: 227472678 }, ns: false, cwr: false, ece: false, urg: false, ack: true, psh: false, rst: false, syn: false, fin: false, window_size: 65535, urgent_pointer: 0, num_options: 0, option_list: [NoOperation, NoOperation, NoOperation, NoOperation, NoOperation] }
DEBUG [catnip::protocols::tcp::peer] Routing to established connection: (Ipv4Endpoint { addr: 10.2.0.10, port: Port16(12345) }, Ipv4Endpoint { addr: 10.2.0.11, port: Port16(50951) })
DEBUG [catnip::protocols::tcp::established::ctrlblk] Established Connection Receiving 64 bytes + TcpHeader { src_port: Port16(50951), dst_port: Port16(12345), seq_num: SeqNumber { value: 3585248092 }, ack_num: SeqNumber { value: 227472678 }, ns: false, cwr: false, ece: false, urg: false, ack: true, psh: false, rst: false, syn: false, fin: false, window_size: 65535, urgent_poin [...]

2022-04-27 15:59 UTC, BrianZill commented on src/protocols/tcp/established/sender/mod.rs
> -                        debug_assert!(cb.user_is_done_sending.get());
Yes.  The comment is remarking on this branch of the "if" statement.

2022-04-27 18:39 UTC, ppenna commented on src/protocols/tcp/established/sender/mod.rs
> +    pub send_unacked: WatchedValue<SeqNumber>,
I'm ok with having this as temporary.

Yeah, this does not hurt performance, because we compile with strong optimizations that force inline of almost everything (that's why our binaries are huge).

Still, you can also use the `#[inline]` directive on functions to be explicit on this even when compiling in debug mode.

2022-04-27 18:39 UTC, ppenna commented on src/protocols/tcp/established/ctrlblk.rs
>          self.receive_next.set(self.receive_next.get() + SeqNumber::from(buf_len as u32));
I see. Thanks for the clarification.

2022-04-27 18:40 UTC, ppenna commented on src/protocols/tcp/established/sender/mod.rs
> +                    bytes_remaining = 0;
Oh, I see. Thanks for the clarification.

2022-04-29 20:54 UTC, BrianZill commented on src/protocols/tcp/established/ctrlblk.rs
> +        return false;
Okay.

2022-04-29 20:54 UTC, BrianZill commented on src/protocols/tcp/established/ctrlblk.rs
>                  //
Yes.

2022-04-29 20:55 UTC, BrianZill commented on src/protocols/tcp/established/ctrlblk.rs
> +                    //
Yes.

2022-04-29 20:55 UTC, BrianZill commented on src/protocols/tcp/established/ctrlblk.rs
> +                    //
Yes.

2022-04-29 20:55 UTC, BrianZill commented on src/protocols/tcp/established/ctrlblk.rs
> +                            //
Yes.

2022-04-29 20:55 UTC, BrianZill commented on src/protocols/tcp/established/ctrlblk.rs
>              //
Yes.

2022-04-29 20:55 UTC, BrianZill commented on src/protocols/tcp/established/ctrlblk.rs
>          //
Yes.

2022-04-29 20:56 UTC, BrianZill commented on src/protocols/tcp/established/ctrlblk.rs
> +    //
This one I left, since it is part of a function description.  I deleted a few more others elsewhere to make up for it :-)

2022-04-29 21:08 UTC, BrianZill commented on src/protocols/tcp/established/sender/mod.rs
> +    pub send_unacked: WatchedValue<SeqNumber>,
As discussed, this is just temporary.  Will be fixed one way or another in future refactoring.  Added ToDo comment to make these private.

2022-04-29 21:09 UTC, BrianZill commented on src/protocols/tcp/established/ctrlblk.rs
> +    pub out_of_order_fin: Cell<Option<SeqNumber>>,
Added ToDo comment to make these private (in future refactoring).

2022-05-01 14:06 UTC, ppenna reviewed
This still breaks the `ping_pong` test of Demikernel, regardless of whether logs are turned on/off.

2022-05-02 19:58 UTC, ppenna approved these changes
@BrianZill could you rebase on `dev` before merging?

2022-05-03 00:54 UTC, BrianZill commented
I created Issue #149 to track the packet/data loss bugs.

2022-05-03 00:54 UTC, merged